site_name: BioDynaMo User Documentation
markdown_extensions:
  - codehilite
  - admonition
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Repository
repo_name: BioDynaMo/biodynamo
repo_url: https://github.com/BioDynaMo/biodynamo
edit_uri: ""

copyright: 'Copyright &copy; The BioDynaMo Project. All Rights Reserved.'

theme:
  name: material
  favicon: images/bdm_logo.png
  logo: images/bdm_logo.png
  palette:
    primary: green
    accent: green
  # feature:
  #   tabs: true

extra:
  social:
    - type: globe
      link: http://biodynamo.web.cern.ch
    - type: github-alt
      link: https://github.com/BioDynaMo/biodynamo

pages:
    - Welcome: index.md
    - Installation: installation.md
    - First Steps: first_steps.md
    - Tutorials:
      - Hello World: hello_world.md
      - Visualization: visualization.md
      - Diffusion: diffusion.md
      - Tumor Concept: jean_tuto.md
      # - Soma Clustering: soma_clustering.md
    - Documentation:
      - Parameter: parameter.md
      - Event: event.md
      - Substance Initialization: substance_initializers.md
      - GPU Acceleration: gpu_acceleration.md
    - Changelog: changelog.md
    - Contact: contact.md
