language: c++

matrix:
  include:
    # Default build on linux
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      group: edge
      env: SCRIPT="util/run-inside-docker.sh ubuntu-16.04 util/travis-ci/default-build.sh"
    # Default build on osx
    - os: osx
      osx_image: xcode10.1
      language: generic
      env: SCRIPT="util/travis-ci/default-build.sh"
    # Code style checks on linux
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      group: edge
      env: SCRIPT="util/run-inside-docker.sh ubuntu-16.04 util/travis-ci/check-code-style.sh"
    # Test development installation on ubuntu-16.04
    - os: linux
      dist: trusty
      sudo: required
      group: edge
      env: SCRIPT="util/travis-ci/installation-test.sh ubuntu-16.04"
    # Test development installation on ubuntu-18.04
    - os: linux
      dist: trusty
      sudo: required
      group: edge
      env: SCRIPT="util/travis-ci/installation-test.sh ubuntu-18.04"
    # Test development installation on centos-7
    - os: linux
      before_install:
        - test -n $CC  && unset CC
        - test -n $CXX && unset CXX
      dist: trusty
      sudo: required
      group: edge
      env: SCRIPT="util/travis-ci/installation-test.sh centos-7"
    # Test development installation on osx
    - os: osx
      osx_image: xcode10.1
      before_install:
       - test -n $CC  && unset CC
       - test -n $CXX && unset CXX
      env: SCRIPT="util/travis-ci/installation-test.sh osx"

script:
  - shell_session_update() { :; };
  - $SCRIPT

services:
  - docker
  - xvfb

notifications:
  slack: cernopenlab:2MzX9lwS6W9nU47MuY1qSmk9

after_failure:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cat /Users/travis/build/BioDynaMo/biodynamo/build/*.log; fi
  - if [ ! "$TRAVIS_OS_NAME" = "osx" ]; then sudo docker exec -it $(docker ps --latest --quiet) cat /home/travis/build/BioDynaMo/biodynamo/build/*.log; fi

env:
  global:
    secure: N2hWo5Yyfwv66vofirJ81Ww19iojqWhHupwkW2UfPWbHG/Mnq1H2nC/3KwbW3UU5iA4zPDFjYY7OWwKZDHjmLJYhD5tAD68EucMdNx0KuyX56r/fCCsioExFlRzqZTgItL7HmuORRKjq/SOX8OI+yW8XOBxGglgUHAJ7B4SWtQ6h8W7OWmW8fLDk7AI1twk6maJiTMGkuHFRp8mA2g0jHf1PdAXIeJ5os3ecMkDJz3LtS+lNP2aF/Udnq8DxQRPK2LXfG5GkzKQP3xli9uNGX8CAadLUOhxmFWMiOimkO5g2L2jeHEqBCTRcHAk68owuDK04ZI9ASznVLrNYsTNofPEhw9Gb7oQFi4ahHDOIqjNIgIPmZFe+nsc4qwZZrohS/QDhVh5BT/YhAcL3tLJ1+HXsp6avv0ILPwjAN++mO6IXoTsZO5kHeAiD293n9SWcFOxIYATLkQF7bNaLkgKIa7yROXc+Ogy6bfQlvhj1mJlc514KfiY+jJS7t6l1thpyBfMi0ITIaPEFyXVoHAa//hrg/XMxgdlRdsJDNaS4ctypgeZ5IjzLXI0W8f+b3xOAgc7pE61TuwO6L77zp1PN9gztx8UVeXxPcwME3kNB0WqEQh/GKVj0ky3fDtBtFUc3Qcztzq+021SSYFUJ8QcZ+tjpDk6ofHO3hdfoPkcB5m0=
