[simulation]
bound_space = true
min_bound = 0
max_bound = 200
leaking_edges = false

[visualization]
# export = false
# export_interval = 1
  
    [[visualize_sim_object]]
      name = "TCell"
      additional_data_members = [ "diameter_", "color_" ]

    [[visualize_sim_object]]
      name = "Monocyte"
      additional_data_members = [ "diameter_", "color_" ]

    [[visualize_diffusion]]
    name = "Antibody"
    gradient = false

# [development]
# statistics = true
